[31;01m/Users/david/python-microscopy/doc/Technical.rst:4: WARNING: toctree contains reference to nonexisting document u'FitModules'[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'sampleInformationDjangoDirect' from module u'PYME.Acquire'; the following exception was raised:
No module named SampleDB2[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'tweeter' from module u'PYME.Acquire'; the following exception was raised:
No module named tweepy[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'multicolourMeta' from module u'PYME.Analysis'; the following exception was raised:
No module named SampleDB2[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'twoColDep' from module u'PYME.Analysis.points'; the following exception was raised:
No module named LatGaussFitFRTC[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'LMAnalysis' from module u'PYME.DSView.modules'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'LMDisplay' from module u'PYME.DSView.modules'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'flowView' from module u'PYME.DSView.modules'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'particleTracking' from module u'PYME.DSView.modules'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'psfGeneration' from module u'PYME.DSView.modules'; the following exception was raised:
cannot import name Property[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'recipes' from module u'PYME.DSView.modules'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'visgui' from module u'PYME.DSView.modules'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/DSView/modules/visgui.py", line 30, in <module>
    from PYME.LMVis.gl_render3D_shaders import LMGLShaderCanvas
  File "/Users/david/python-microscopy/PYME/LMVis/gl_render3D_shaders.py", line 29, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'deccs' from module u'PYME.Deconv.experimental'; the following exception was raised:
cannot import name fftwWisdom[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'deccs2' from module u'PYME.Deconv.experimental'; the following exception was raised:
cannot import name fftwWisdom[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'deccs_mc' from module u'PYME.Deconv.experimental'; the following exception was raised:
cannot import name fftwWisdom[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'BGSDataSourceX' from module u'PYME.IO.DataSources'; the following exception was raised:
No module named BGSDataSourceX[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'h5rFormatDef' from module u'PYME.IO.FileUtils'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/IO/FileUtils/h5rFormatDef.py", line 29, in <module>
    h5ResultsFile = tables.open_file(resultsFilename, 'w')
NameError: name 'resultsFilename' is not defined
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'pointSetGeneration' from module u'PYME.LMVis.Extras'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'snapshot' from module u'PYME.LMVis.Extras'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/Extras/snapshot.py", line 25, in <module>
    from OpenGL.GL import GL_LUMINANCE, GL_RGB
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'VisGUI' from module u'PYME.LMVis'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'gl_offScreenHandler' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/gl_offScreenHandler.py", line 21, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'gl_render' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/gl_render.py", line 28, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'gl_render3D' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/gl_render3D.py", line 29, in <module>
    from OpenGL import GLUT
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GLUT/__init__.py", line 2, in <module>
    from OpenGL.raw.GLUT import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/raw/GLUT/__init__.py", line 6, in <module>
    from OpenGL.raw.GLUT.constants import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/raw/GLUT/constants.py", line 7, in <module>
    from OpenGL import platform, arrays
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'gl_render3D_shaders' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/gl_render3D_shaders.py", line 29, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layer_panel' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layer_panel.py", line 6, in <module>
    import PYME.ui.layerFoldPanel as lfp
  File "/Users/david/python-microscopy/PYME/ui/layerFoldPanel.py", line 2, in <module>
    from PYME.LMVis.layers import pointcloud, mesh
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layer_wrapper' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layer_wrapper.py", line 1, in <module>
    from . import layers
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.AxesOverlayLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.LUTOverlayLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.OverlayLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.QuadTreeRenderLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.ScaleBarOverlayLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.ScaleBoxOverlayLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.SelectionOverlayLayer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.base' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.image_layer' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.mesh' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.octree' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.pointcloud' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layers.tracks' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'pipeline' from module u'PYME.LMVis'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'pointSettingsPanel' from module u'PYME.LMVis'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'quadTreeSettings' from module u'PYME.LMVis'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'DefaultShaderProgram' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'GLProgram' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'GouraudShaderProgram' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GouraudShaderProgram.py", line 22, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'PointSpriteShaderProgram' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/PointSpriteShaderProgram.py", line 23, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'TesselShaderProgram' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/TesselShaderProgram.py", line 23, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glPolygonMode, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'WireFrameShaderProgram' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/WireFrameShaderProgram.py", line 23, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glPolygonMode, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'shader_program' from module u'PYME.LMVis.shader_programs'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/shader_program.py", line 24, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'gl_test_apps' from module u'PYME.LMVis.tests'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/tests/gl_test_apps.py", line 29, in <module>
    from PYME.LMVis.gl_render3D_shaders import LMGLShaderCanvas
  File "/Users/david/python-microscopy/PYME/LMVis/gl_render3D_shaders.py", line 29, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'triBlobs' from module u'PYME.LMVis'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'view_clipping_pane' from module u'PYME.LMVis'; the following exception was raised:
cannot import name BaseEnum[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'visCore' from module u'PYME.LMVis'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/LMVis/visCore.py", line 17, in <module>
    from PYME.LMVis import gl_render3D as gl_render
  File "/Users/david/python-microscopy/PYME/LMVis/gl_render3D.py", line 29, in <module>
    from OpenGL import GLUT
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GLUT/__init__.py", line 2, in <module>
    from OpenGL.raw.GLUT import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/raw/GLUT/__init__.py", line 6, in <module>
    from OpenGL.raw.GLUT.constants import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/raw/GLUT/constants.py", line 7, in <module>
    from OpenGL import platform, arrays
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:117: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.IntegerIDRule.bid'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:117: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.IntegerIDRule.info'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:117: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.IntegerIDRule.make_range_available'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:117: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.IntegerIDRule.mark_complete'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:18: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.RuleServer.add_integer_id_rule'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:18: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.RuleServer.bid_on_tasks'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:18: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.RuleServer.get_queues'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:18: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.RuleServer.handin'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:18: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.RuleServer.release_rule_tasks'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:18: WARNING: toctree references unknown document u'api/PYME.cluster.ruleserver.RuleServer.task_advertisements'[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'LatGaussFitlmR' from module u'PYME.localization.FitFactories'; the following exception was raised:
No module named levmar_gfit[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'ofind_xcorr_fw' from module u'PYME.localization'; the following exception was raised:
cannot import name util[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'VolProj' from module u'PYME.misc'; the following exception was raised:
cannot import name Interface[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'calenderApi' from module u'PYME.misc'; the following exception was raised:
No module named gflags[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'hillcurve' from module u'PYME.misc'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/misc/hillcurve.py", line 43, in <module>
    ratio_control, stress_control = loadtxt('control.csv').T
  File "/Users/david/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/david/anaconda/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/david/anaconda/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: control.csv not found.
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'memmap' from module u'PYME.misc'; the following exception was raised:
No module named guppy[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'tempDB' from module u'PYME.misc'; the following exception was raised:
No module named MySQLdb[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'tempLoggerDB' from module u'PYME.misc'; the following exception was raised:
No module named MySQLdb[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'html_recipe_editor' from module u'PYME.recipes'; the following exception was raised:
cannot import name TraitDictEvent[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'skfilters' from module u'PYME.recipes'; the following exception was raised:
No module named filters[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'custom_traits_editors' from module u'PYME.ui'; the following exception was raised:
No module named editor[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'layerFoldPanel' from module u'PYME.ui'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/ui/layerFoldPanel.py", line 2, in <module>
    from PYME.LMVis.layers import pointcloud, mesh
  File "/Users/david/python-microscopy/PYME/LMVis/layers/__init__.py", line 22, in <module>
    from .AxesOverlayLayer import AxesOverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/AxesOverlayLayer.py", line 21, in <module>
    from PYME.LMVis.layers.OverlayLayer import OverlayLayer
  File "/Users/david/python-microscopy/PYME/LMVis/layers/OverlayLayer.py", line 24, in <module>
    from PYME.LMVis.shader_programs.DefaultShaderProgram import DefaultShaderProgram
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/DefaultShaderProgram.py", line 24, in <module>
    from PYME.LMVis.shader_programs.GLProgram import GLProgram, GL_VERTEX_SHADER, GL_FRAGMENT_SHADER, glUseProgram, \
  File "/Users/david/python-microscopy/PYME/LMVis/shader_programs/GLProgram.py", line 22, in <module>
    from OpenGL.GL import *
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/david/anaconda/lib/python2.7/site-packages/OpenGL/platform/__init__.py", line 29, in _load
    plugin = plugin_class()
TypeError: 'NoneType' object is not callable
[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'install_dependencies' from module u'PYME.util'; the following exception was raised:
No module named apt[39;49;00m
[31;01mWARNING: autodoc: failed to import module u'pymelauncher' from module u'PYME.util'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/david/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/Users/david/python-microscopy/PYME/util/pymelauncher.py", line 46, in <module>
    sys.exit(subprocess.call(args, env=env))
  File "/Users/david/anaconda/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/david/anaconda/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/david/anaconda/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[39;49;00m
[31;01m/Users/david/python-microscopy/doc/Installation/Installation.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/Installation/InstallationWithAnacondaNoConsole.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/Technical.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.points.DistHist.distHistThreaded.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.points.traveling_salesperson.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.tileviewer.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/modules.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/cluster/clusterFilesystem.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/cluster/cluster_install.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/dh5view.rst: WARNING: document isn't included in any toctree[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.misc.shellutils.rst:48: WARNING: Citation [Rd75597b4d042-2] is not referenced.[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.MultiPointScanner.PointScanner.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.pointScanner.PointScanner.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.pointScanner.PointScanner3D.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.tiler.CircularTiler.genCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetAqProtocolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetSpoolDirButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartSpoolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartStackButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStopSpoolingButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.UpdateFreeSpace'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetAqProtocolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetSpoolDirButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartSpoolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartStackButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStopSpoolingButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.UpdateFreeSpace'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.multiview_select.MultiviewSelect.on_toggle'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.QueueAction'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.QueueAction'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.EventLogger.logEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.EventLogger.logEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.Spooler.OnFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.Spooler.StopSpool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.LaunchAnalysis'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.SetProtocol'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.SetSpoolDir'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.SetSpoolMethod'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.StartSpooling'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.StopSpooling'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.get_free_space'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.EventLogger.logEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.OnFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStartLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStopLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.fakeTime'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.OnFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStartLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStopLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.fakeTime'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.acquiremainframe.PYMEMainFrame.AddAqTool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.acquiremainframe.PYMEMainFrame.AddCamTool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.acquiremainframe.PYMEMainFrame.AddTool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.Notify'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.Prepare'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.checkHardware'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.getFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.getReqMemChans'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.onExpReady'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.purge'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.start'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateHandler.setValue'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.registerChangeListener'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.registerHandler'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.setItem'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.setItems'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.update'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.AddVoxelSizeSetting'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.GenStartMetadata'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.GetActiveCameraName'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.GetPixelSize'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.PanCamera'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.SetVoxelSize'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.centre_roi_on'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.genStatus'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.get_roi_offset'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.register_camera'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.register_piezo'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.satCheck'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.startFrameWrangler'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.turnAllLasersOff'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Acquire.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.stackSettings.StackSettings.SetDirection'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA.FourierPropagatorClipHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA.FourierPropagatorHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA.FourierPropagatorHNA.propagate_r'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA2.FourierPropagatorClipHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA2.FourierPropagatorHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA2.FourierPropagatorHNA.propagate_r'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.Tracking.tracking.Tracker.calcLinkageMatrix'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin2Model.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin3Model.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin3zModel.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.linModel.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.density_filter.DensityFilter.__call__'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.tile_pyramid.ImagePyramid.get_oversize_tile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.points.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin2Model.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.points.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin3Model.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.points.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin3zModel.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.Analysis.points.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.linModel.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.composite.compositor.OnApplyShiftmap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.composite.compositor.RemapData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.filtering.filterer.OnAverageFramesByStep'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.graphViewPanel.MyNavigationToolbar.draw_rubberband'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.psfExtraction.PsfExtractor.OnCalibrateMultiview'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.pupilView.MyNavigationToolbar.draw_rubberband'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.vis3D.visualiser.save_stl'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.vis3D.visualiser.save_u3d'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.DSView.modules.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.vis3D.visualiser.save_x3d'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.IO.DataSources.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getEvents'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.IO.DataSources.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getNumSlices'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.IO.DataSources.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getSlice'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.IO.DataSources.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getSliceShape'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.animation.VideoPanel.on_edit'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnClumpDBSCAN'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnFindMixedClusters'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnMeasureClusters'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnNearestNeighbor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.flagZMotionArtifacts.motionFlagger.OnIDTransient'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnCalibrateShifts'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnCheckAstigmatismCalibration'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnFindClumps'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnFold'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnMapAstigmaticZ'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnMergeClumps'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnShiftCorrectFolded'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.objectMeasurements.ObjectMeasurer.OnGetIDs'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.scaleBox.ScaleBoxPanel.pick_color'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.surface_fitting.SurfaceFitter.OnFitQuadraticPatches'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.ShaderProgramFactory.ShaderProgramFactory.get_program'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.shader_loader.ShaderLoader.read_file'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.shader_loader.ShaderLoader.read_file_with_path'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.HarmonicCellBackground.get_coordinates'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add_probe'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add_probe'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObjectContainer.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.progGraph.progPanel.draw'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.animation.VideoPanel.on_edit'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnClumpDBSCAN'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnFindMixedClusters'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnMeasureClusters'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnNearestNeighbor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.flagZMotionArtifacts.motionFlagger.OnIDTransient'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnCalibrateShifts'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnCheckAstigmatismCalibration'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnFindClumps'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnFold'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnMapAstigmaticZ'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnMergeClumps'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnShiftCorrectFolded'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.objectMeasurements.ObjectMeasurer.OnGetIDs'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.scaleBox.ScaleBoxPanel.pick_color'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.Extras.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.surface_fitting.SurfaceFitter.OnFitQuadraticPatches'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.shader_programs.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.ShaderProgramFactory.ShaderProgramFactory.get_program'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.shader_programs.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.shader_loader.ShaderLoader.read_file'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.shader_programs.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.shader_loader.ShaderLoader.read_file_with_path'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.HarmonicCellBackground.get_coordinates'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add_probe'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add_probe'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.LMVis.tests.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObjectContainer.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.do_GET'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.list_directory'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.log_error'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.log_message'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.log_request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.send_error'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.HTTPDataServer.PYMEHTTPRequestHandler.send_head'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.dataserver_wsgi.dataserver.do_GET'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.dataserver_wsgi.dataserver.do_HEAD'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.dataserver_wsgi.dataserver.guess_type'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.dataserver_wsgi.dataserver.list_directory'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.dataserver_wsgi.dataserver.translate_path'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.bid'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.info'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.make_range_available'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.mark_complete'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.add_integer_id_rule'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.bid_on_tasks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.get_queues'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.handin'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.release_rule_tasks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.task_advertisements'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.taskWorkerHTTP.taskWorker.ioLoop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DAVRequestHandler.path_elem'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DAVRequestHandler.path_elem_prev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DAVRequestHandler.split_path'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DAVServer.finish_request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DirCollection.findMember'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DirCollection.getMembers'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DirCollection.recvMember'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.DirCollection.sendData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.FileMember.getProperties'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.FileMember.sendData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.Tag.addChild'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.TempDirCollection.getProperties'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.XMLDict_Parser.builddict'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.webdav.XMLDict_Parser.processTag'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:125:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.bid'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:125:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.info'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:125:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.make_range_available'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.IntegerIDRule:125:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.IntegerIDRule.mark_complete'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:28:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.add_integer_id_rule'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:28:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.bid_on_tasks'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:28:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.get_queues'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:28:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.handin'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:28:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.release_rule_tasks'[39;49;00m
[31;01m/Users/david/python-microscopy/PYME/cluster/ruleserver.py:docstring of PYME.cluster.ruleserver.RuleServer:28:<autosummary>:: WARNING: toctree contains reference to nonexisting document u'api/PYME.cluster.ruleserver.RuleServer.task_advertisements'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.ruleserver.rst:44: WARNING: Could not lex literal_block as "json". Highlighting skipped.[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.ruleserver.rst:58: WARNING: Could not lex literal_block as "json". Highlighting skipped.[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.ruleserver.rst:70: WARNING: Could not lex literal_block as "json". Highlighting skipped.[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.cluster.ruleserver.rst:82: WARNING: Could not lex literal_block as "json". Highlighting skipped.[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.interpG'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubeSInterpolatorP.CSInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubeSInterpolatorP.CSInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubicSplineInterpolator.CubicSplineInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubicSplineInterpolator.CubicSplineInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.interpG'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearPInterpolatorP.LinearInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearPInterpolatorP.LinearInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussFitFR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussGPUFitFR.GaussianFitFactory.FindAndFit'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussGPUFitFR.GaussianFitFactory.FromPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.BeadConvolvedAstigGaussFit.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.DumbellFitR.DumbellFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.FromPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.FromPoints'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getMultiviewROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getSplitROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.GaussFitConstrR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.LatGaussFitFR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.error'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.evalParams'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.fromMDFile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotRes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotResSimp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.runTests'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.error'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.evalParams'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.fromMDFile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotRes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotResSimp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.runTests'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind3d.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_nofilt.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_pri.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_split.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_xcorr.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.BufferManager.updateBuffers'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.correctImage'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.getDarkMap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.getFlatfieldMap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.getVarianceMap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.fitTask.calcSigma'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.interpG'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubeSInterpolatorP.CSInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubeSInterpolatorP.CSInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubicSplineInterpolator.CubicSplineInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubicSplineInterpolator.CubicSplineInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.interpG'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearPInterpolatorP.LinearInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearPInterpolatorP.LinearInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussFitFR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussGPUFitFR.GaussianFitFactory.FindAndFit'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussGPUFitFR.GaussianFitFactory.FromPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.BeadConvolvedAstigGaussFit.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.DumbellFitR.DumbellFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.FromPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.FromPoints'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getMultiviewROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getSplitROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.GaussFitConstrR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.localization.FitFactories.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.LatGaussFitFR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.misc.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.TiffImagePlugin.TiffImageFile.seek'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.misc.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.TiffImagePlugin.TiffImageFile.tell'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.misc.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.pyme_zeroconf.PatchedServiceInfo.request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.misc.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.pyme_zeroconf.PatchedServiceInfo.request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.Filter.dsviewer_plugin_callback'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleBase.apply'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleBase.apply_simple'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleBase.execute'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.gather_outputs'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.loadInput'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.update_from_yaml'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.OutputModule.execute'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.OutputModule.generate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.as_html'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.plot'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.as_html'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.plot'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.CSVOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.HDFOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.ImageOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.RGBImageOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.ReportForEachOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.ReportOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.XLSOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.processing.Deconvolve.GetDec'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.processing.DeconvolveMotionCompensating.GetDec'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.processing.ProjectOnVector.do_proj'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.tracking.TrackFeatures.Track'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.recipes.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.tracking.TrackFeatures.TrackWithPipeline'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.AUIFrame.AUIFrame.AddMenuItem'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.AUIFrame.AUIFrame.AddPage'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.AUIFrame.AUIFrame.CreateFoldPanel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.CloseEditor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.OnChar'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.OnLeftDown'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.ui.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.OpenEditor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.util.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.__call__'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.util.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.format'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.util.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.__call__'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.util.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.format'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/api/PYME.util.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.webframework.JSONAPIRequestHandler.log_request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.MultiPointScanner.PointScanner.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.pointScanner.PointScanner.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.pointScanner.PointScanner3D.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Utils.tiler.CircularTiler.genCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetAqProtocolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetSpoolDirButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartSpoolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartStackButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStopSpoolingButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.UpdateFreeSpace'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetAqProtocolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBSetSpoolDirButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartSpoolButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStartStackButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.OnBStopSpoolingButton'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.HDFSpoolFrame.PanSpool.UpdateFreeSpace'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ui.multiview_select.MultiviewSelect.on_toggle'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.QueueAction'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.QueueAction'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.ActionManager.ActionManager.Tick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.EventLogger.logEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.EventLogger.logEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.Spooler.OnFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.HDFSpooler.Spooler.StopSpool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.LaunchAnalysis'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.SetProtocol'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.SetSpoolDir'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.SetSpoolMethod'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.StartSpooling'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.StopSpooling'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.SpoolController.SpoolController.get_free_space'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.EventLogger.logEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.OnFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStartLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStopLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.fakeTime'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.OnFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStartLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.doStopLog'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.Spooler.Spooler.fakeTime'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.acquiremainframe.PYMEMainFrame.AddAqTool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.acquiremainframe.PYMEMainFrame.AddCamTool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.acquiremainframe.PYMEMainFrame.AddTool'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.Notify'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.Prepare'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.checkHardware'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.getFrame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.getReqMemChans'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.onExpReady'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.purge'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.start'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.frameWrangler.FrameWrangler.stop'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateHandler.setValue'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.registerChangeListener'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.registerHandler'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.setItem'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.setItems'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.StateManager.update'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.AddVoxelSizeSetting'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.GenStartMetadata'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.GetActiveCameraName'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.GetPixelSize'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.PanCamera'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.SetVoxelSize'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.centre_roi_on'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.genStatus'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.get_roi_offset'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.register_camera'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.register_piezo'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.satCheck'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.startFrameWrangler'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.microscope.microscope.turnAllLasersOff'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Acquire.stackSettings.StackSettings.SetDirection'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA.FourierPropagatorClipHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA.FourierPropagatorHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA.FourierPropagatorHNA.propagate_r'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA2.FourierPropagatorClipHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA2.FourierPropagatorHNA.propagate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.PSFGen.fourierHNA2.FourierPropagatorHNA.propagate_r'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.Tracking.tracking.Tracker.calcLinkageMatrix'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin2Model.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin3Model.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.lin3zModel.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.points.twoColour.linModel.ev'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.density_filter.DensityFilter.__call__'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Analysis.tile_pyramid.ImagePyramid.get_oversize_tile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.composite.compositor.OnApplyShiftmap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.composite.compositor.RemapData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.filtering.filterer.OnAverageFramesByStep'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.graphViewPanel.MyNavigationToolbar.draw_rubberband'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.psfExtraction.PsfExtractor.OnCalibrateMultiview'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.pupilView.MyNavigationToolbar.draw_rubberband'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.vis3D.visualiser.save_stl'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.vis3D.visualiser.save_u3d'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.modules.vis3D.visualiser.save_x3d'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.arrayViewPanel.ArrayViewPanel.CopyImage'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.arrayViewPanel.ArrayViewPanel.GrabPNGToBuffer'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.dsviewer.DSViewFrame.LoadModule'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.DSView.fitInfo.fitDispPanel.draw'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingFFTW.Afunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingFFTW.Ahfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingFFTW.Lfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingFFTW.Lhfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingFFTW.psf_calc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingNP.Afunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingNP.Ahfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingNP.Lfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingNP.Lhfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ClassicMappingNP.psf_calc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.DeconvMappingBase.Afunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.DeconvMappingBase.Ahfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.DeconvMappingBase.Lfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.DeconvMappingBase.Lhfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.DeconvMappingBase.prep'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.DeconvMappingBase.psf_calc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ICTMDeconvolution.deconv'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ICTMDeconvolution.deconvp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ICTMDeconvolution.sim_pic'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ICTMDeconvolution.startGuess'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.ICTMDeconvolution.subsearch'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.SpatialConvolutionMapping.Afunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.SpatialConvolutionMapping.Ahfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.SpatialConvolutionMapping.Lfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.SpatialConvolutionMapping.Lhfunc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.dec.dec_4pi.psf_calc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.richardsonLucy.RichardsonLucyDeconvolution.deconv'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.richardsonLucy.RichardsonLucyDeconvolution.deconvp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.richardsonLucy.RichardsonLucyDeconvolution.startGuess'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.richardsonLucyMV.MultiviewRichardsonLucy.deconv'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.richardsonLucyMVM.MotionCompensatingRichardsonLucy.deconv'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.richardsonLucyMVM.MotionCompensatingRichardsonLucy.pd'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.wiener.dec_wiener.deconv'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.Deconv.wiener.dec_wiener.psf_calc'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getEvents'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getNumSlices'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getSlice'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.DataSources.BaseDataSource.BaseDataSource.getSliceShape'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.GetSimpleString'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.WriteSimple'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.copyEntriesFrom'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.getEntry'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.getEntryNames'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.getOrDefault'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.keys'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.mergeEntriesFrom'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.MetaDataHandler.MDHandlerBase.setEntry'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.clusterExport.ImageFrameSource.spoolData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.clusterExport.ImageFrameSource.spoolImageFromFile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.dcimg.DCIMGFile.get_frame'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.h5rFile.H5RFile.fileFitResult'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.h5rFile.H5RFile.updateMetadata'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.image.ImageStack.Load'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.image.ImageStack.Save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.image.ImageStack.SetData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.tabular.MappingFilter.addColumn'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.tabular.MappingFilter.addVariable'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.IO.tabular.TabularBase.to_recarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.animation.VideoPanel.on_edit'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnClumpDBSCAN'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnFindMixedClusters'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnMeasureClusters'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.clusterAnalysis.ClusterAnalyser.OnNearestNeighbor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.flagZMotionArtifacts.motionFlagger.OnIDTransient'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnCalibrateShifts'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnCheckAstigmatismCalibration'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnFindClumps'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnFold'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnMapAstigmaticZ'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnMergeClumps'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.multiviewMapping.MultiviewMapper.OnShiftCorrectFolded'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.objectMeasurements.ObjectMeasurer.OnGetIDs'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.scaleBox.ScaleBoxPanel.pick_color'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.Extras.surface_fitting.SurfaceFitter.OnFitQuadraticPatches'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.ShaderProgramFactory.ShaderProgramFactory.get_program'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.shader_loader.ShaderLoader.read_file'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.shader_programs.shader_loader.ShaderLoader.read_file_with_path'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.HarmonicCellBackground.get_coordinates'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add_probe'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.add_probe'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObject.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.tests.gl_test_objects.TestObjectContainer.translate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.LMVis.progGraph.progPanel.draw'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.DSTaskQueue.DSTaskQueue.getQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.DSTaskQueue.DSTaskQueue.getTask'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.DSTaskQueue.DSTaskQueue.getTasks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFResultsTaskQueue.fileResult'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFResultsTaskQueue.fileResults'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFResultsTaskQueue.getQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFResultsTaskQueue.fileResult'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFResultsTaskQueue.fileResults'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFResultsTaskQueue.getQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFTaskQueue.getQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFTaskQueue.getTask'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.HDFTaskQueue.HDFTaskQueue.getTasks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskQueue.TaskQueue.getTask'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskQueue.TaskQueue.setPopFcn'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskQueue.TaskQueueWithData.getQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskQueue.TaskQueueWithData.setQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.addQueueEvents'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.getQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.getQueueMetaData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.getQueueMetaDataKeys'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.getTask'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.getTasks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.logQueueEvent'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.postTask'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.releaseTasks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.setQueueData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.setQueueMetaData'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ParallelTasks.taskServerZC.TaskQueueSet.setQueueMetaDataEntries'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.save_attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.segments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.subblocks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.save_attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.segments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.subblocks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.save_attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.segments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.subblocks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.save_attachments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.segments'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.czifile.CziFile.subblocks'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor3Raw.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor3Raw.close'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor3Raw.filename'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor3Raw.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor3Raw.close'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor3Raw.filename'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor2Raw.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor2Raw.close'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor2Raw.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.fcsfiles.ConfoCor2Raw.close'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.tifffile.TIFFfile.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.tifffile.TIFFfile.close'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.tifffile.TIFFfile.asarray'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.gohlke.tifffile.TIFFfile.close'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.TextCtrlAutoComplete.GetSortImages'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.TextCtrlAutoComplete.SetChoices'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.TextCtrlAutoComplete.SetMultipleChoices'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.TextCtrlAutoComplete.onKeyDown'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.TextCtrlAutoComplete.onListClick'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.test.match'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.test.onBtDynamicChoices'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.TextCtrlAutoComplete.test.selectCallback'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.GetColumnSorter'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.GetColumnWidths'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.GetSecondarySortValues'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.GetSortImages'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.GetSortState'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.OnSortOrderChanged'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ColumnSorterMixin.SortListItems'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlAutoWidthMixin.resizeLastColumn'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlAutoWidthMixin.setResizeColumn'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlAutoWidthMixin.resizeLastColumn'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlAutoWidthMixin.setResizeColumn'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlSelectionManagerMix.afterPopupMenu'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlSelectionManagerMix.getPopupMenu'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListCtrlSelectionManagerMix.setPopupMenu'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListRowHighlighter.RefreshRows'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListRowHighlighter.SetHighlightColor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListRowHighlighter.SetHighlightMode'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListRowHighlighter.RefreshRows'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListRowHighlighter.SetHighlightColor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.ListRowHighlighter.SetHighlightMode'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.TextEditMixin.CloseEditor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.TextEditMixin.OnChar'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.TextEditMixin.OnLeftDown'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.listctrlMixins.TextEditMixin.OpenEditor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.BitPacker.pack'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.BitPacker.pack'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.BitUnpacker.unpack'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.BitUnpacker.unpack'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.ByteDecoder.decodefrombytes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.ByteDecoder.decodefrombytes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.ByteEncoder.encodetobytes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.ByteEncoder.encodetobytes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Decoder.code_size'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Decoder.decode'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Decoder.code_size'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Decoder.decode'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Encoder.code_size'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Encoder.encode'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Encoder.flush'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Encoder.code_size'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Encoder.encode'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.Encoder.flush'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.PagingDecoder.decodepages'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.PagingDecoder.next_page'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.lzw.PagingEncoder.encodepages'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.contrib.wxPlotPanel.PlotPanel.SetColor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CSInterpolator.CSInterpolator.interpG'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubeSInterpolatorP.CSInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubeSInterpolatorP.CSInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubicSplineInterpolator.CubicSplineInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.CubicSplineInterpolator.CubicSplineInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearInterpolator.LinearInterpolator.interpG'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearPInterpolatorP.LinearInterpolator.getCoords'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.Interpolators.LinearPInterpolatorP.LinearInterpolator.interp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussFitFR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussGPUFitFR.GaussianFitFactory.FindAndFit'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.AstigGaussGPUFitFR.GaussianFitFactory.FromPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.BeadConvolvedAstigGaussFit.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.DumbellFitR.DumbellFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.FromPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.FromPoints'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getMultiviewROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.FFBase.FFBase.getSplitROIAtPoint'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.GaussFitConstrR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.FitFactories.LatGaussFitFR.GaussianFitFactory.evalModel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.error'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.evalParams'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.fromMDFile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotRes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotResSimp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.runTests'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.error'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.evalParams'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.fromMDFile'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotRes'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.plotResSimp'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.Test.fitTestJigSCMOS.fitTestJig.runTests'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind3d.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_nofilt.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_pri.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_split.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.ofind_xcorr.ObjectIdentifier.FindObjects'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.BufferManager.updateBuffers'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.correctImage'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.getDarkMap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.getFlatfieldMap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.CameraInfoManager.getVarianceMap'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.localization.remFitBuf.fitTask.calcSigma'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.TiffImagePlugin.TiffImageFile.seek'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.TiffImagePlugin.TiffImageFile.tell'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.pyme_zeroconf.PatchedServiceInfo.request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.misc.pyme_zeroconf.PatchedServiceInfo.request'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.Filter.dsviewer_plugin_callback'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleBase.apply'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleBase.apply_simple'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleBase.execute'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.gather_outputs'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.loadInput'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.ModuleCollection.update_from_yaml'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.OutputModule.execute'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.base.OutputModule.generate'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.as_html'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.plot'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.as_html'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.graphing.Plot.plot'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.CSVOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.HDFOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.ImageOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.RGBImageOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.ReportForEachOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.ReportOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.output.XLSOutput.save'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.processing.Deconvolve.GetDec'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.processing.DeconvolveMotionCompensating.GetDec'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.processing.ProjectOnVector.do_proj'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.tracking.TrackFeatures.Track'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.recipes.tracking.TrackFeatures.TrackWithPipeline'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.AUIFrame.AUIFrame.AddMenuItem'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.AUIFrame.AUIFrame.AddPage'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.AUIFrame.AUIFrame.CreateFoldPanel'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.CloseEditor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.OnChar'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.OnLeftDown'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.ui.MetadataTree.TextEditMixin.OpenEditor'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.__call__'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.format'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.__call__'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.mProfile.colorize_db_t.Parser.format'[39;49;00m
[31;01m/Users/david/python-microscopy/doc/index.rst:: WARNING: toctree contains reference to nonexisting document u'api/PYME.util.webframework.JSONAPIRequestHandler.log_request'[39;49;00m
